.github/workflows/test.yml
src/core/packager.ts
src/utils/gitignoreUtils.ts
tests/utils/gitignoreUtils.test.ts
vite.config.mts

This PR makes improvements to the GitHub Actions workflow and TypeScript code.
1. **GitHub Actions Workflow:**
- Changed `npm i` to `npm ci` for clean installation of dependencies.
- Added matrix testing for multiple OSes (`ubuntu-latest`, `windows-latest`, `macos-latest`) and Node.js versions (`16.x`, `18.x`, `20.x`).
- Added `CI_OS` environment variable to indicate the runner OS.
2. **TypeScript Code:**
- Added `IgnoreFilter` type in `gitignoreUtils.ts`.
- Updated `ignoreFilter` argument type to `IgnoreFilter` in `packDirectory` function.
- Added new test cases for `createIgnoreFilter` function.
3. **Test Coverage:**
- Included all files in the `src` directory in the coverage target in `vite.config.mts`.

chore: Add ignore filter tests and improve ci

---

README.md
package-lock.json
package.json
repopack.config.json
src/config/defaultConfig.ts
src/core/outputGenerator.ts
src/core/packager.ts
src/types/index.ts
src/utils/fileHandler.ts
src/utils/fileManipulator.ts
src/utils/gitignoreUtils.ts
tests/utils/fileHandler.test.ts
tests/utils/fileManipulator.test.ts

Fix: #2
1. Added `removeComments` option to the configuration
2. Implemented comment removal for various file types (e.g., Python, JavaScript, HTML, CSS)
3. Updated README with information about the new feature
4. Added tests for the new functionality
Set `output.removeComments` to `true` in your `repopack.config.json` file to enable comment removal:
```json
{
"output": {
"removeComments": true
}
}
```
This feature helps reduce the size of the output file and focuses on the essential code content, which can be beneficial for AI processing.

feat: Add comment remove feature

---

README.md
package-lock.json
package.json
src/cli/cliOutput.ts
src/cli/index.ts
src/core/packager.ts
src/utils/secretLintUtils.ts
tests/utils/secretLintUtils.test.ts

This PR integrates SecretLint into Repopack to detect potentially sensitive information during the packing process.
- Added SecretLint utilities in `secretLintUtils.ts`
- Updated `packager.ts` to perform security checks
- Modified CLI output to display security check results
To enhance the security of packed repositories by alerting users to potential secrets or sensitive data in their files.

feat: Implement SecretLint integration for enhanced security checks

---

src/utils/fileManipulator.ts
tests/utils/fileManipulator.test.ts

This PR fixes two issues:
1. `rtrimLines` now preserves newlines and empty lines.
2. Comment removal now correctly handles `#` comments.
```diff
// In src/utils/fileManipulator.ts
function rtrimLines(content: string): string {
-  return content.replace(/\s+$/gm, '');
+  return content.replace(/[ \t]+$/gm, '');
}
// In relevant comment removal functions
- content.replace(/\/\/.*|\/\*[\s\S]*?\*\//g, '');
+ content.replace(/\/\/.*|\/\*[\s\S]*?\*\/|#.*/g, '');
```

Fix rtrimLines function and improve comment removal

---

README.md
src/core/outputGenerator.ts
src/core/packager.ts
src/utils/fileHandler.ts
tests/core/outputGenerator.test.ts
tests/core/packager.test.ts
tests/utils/fileHandler.test.ts

- Added a note about binary file handling in the "Ignore Patterns" section of README.md
- Updated the code to include binary file paths in the "Repository Structure" section of the output
- To clearly communicate how binary files are processed to users
- To provide a complete overview of the repository structure, including binary files
- To enhance transparency about the content and structure of the packed repository

Clarify binary file handling in README and output

---

README.md
src/cli/index.ts
src/config/configValidator.ts
src/types/index.ts
tests/config/configValidator.test.ts

This PR adds a new CLI option `--style` to allow users to specify the output style (plain or xml) directly from the command line. It also includes validation to ensure only valid styles are accepted in both the CLI and config file.
- Added `--style` option to CLI
- Updated config validation to check for valid style values

feat(cli): Add CLI option for output style

---

.gitignore
repopack.config.json
src/core/packager.ts

The file specified by `output.filePath` is currently included in the output itself, causing a recursive issue.
Modify `getFilePaths` function in `src/core/packager.ts` to exclude the output file from processing.

Exclude output file from being included in the output

---

src/core/outputGenerator.ts

This PR removes XML escaping from the output generator to improve readability and AI comprehension of the generated output.
- Removed XML escaping for file paths and contents in repository files
Note: This change assumes that the input data (file paths, contents, etc.) does not contain characters that would break XML syntax. If there's a possibility of such characters, we may need to implement a more robust solution, such as using CDATA sections for file contents.

Remove XML escaping from output generator

---

README.md
package-lock.json
package.json
src/cli/cliOutput.ts
src/cli/index.ts
src/core/packager.ts
tests/core/tokenCounter.test.ts

This PR adds support for token counting and CLI display using the `tiktoken` library. Provides token counts for individual files and the entire repository, which is useful for working within context limits.
Currently set to use `cl100k_base` as the encoder ([used for GPT-4, etc.](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb)). Could add an option for customizing which encoder to use, but felt like the `cl100k_base` is "good enough" (getting >95% token count accuracy has very limited value IMO) and limits option scope.
Decided on the `tiktoken` library based on [high-level benchmarks](https://github.com/transitive-bullshit/compare-tokenizers), higher NPM weekly downloads, and fairly decent commit activity.
- Added `tiktoken` as a …

feat(cli): Add token counts for CLI outputs

---

.repopackignore
README.md
package-lock.json
package.json
src/cli/cliRunner.ts
src/cli/commands/defaultCommandRunner.ts
src/cli/commands/initCommandRunner.ts
src/cli/commands/versionCommandRunner.ts

This PR introduces a new `--init` command to Repopack, allowing users to interactively create a basic `repopack.config.json` file. The key changes include:
The `--init` command now allows users to easily set up their initial Repopack configuration by prompting for:
- Output file path
- Output style (plain or XML)
This addition simplifies the process of getting started with Repopack, especially for new users.

Add `--init` command for interactive configuration setup

---

src/core/output/outputGenerator.ts
src/core/packager.ts
src/core/security/securityCheckRunner.ts
tests/core/output/outputGenerator.test.ts
tests/core/packager.test.ts
tests/core/security/secretLintRunner.test.ts

1. Modified `generateOutput` to return a string instead of writing to a file directly.
4. Extracted `runSecurityCheck` function from `pack` for better organization.

Refactor Output Generation and Security Check Processes

---

README.md
src/cli/actions/initActionRunner.ts
src/cli/cliRunner.ts
src/config/configLoader.ts
src/config/globalDirectory.ts
tests/cli/actions/initActionRunner.test.ts
tests/config/configLoader.test.ts
tests/config/globalDirectory.ts
tests/testing/testUtils.ts

related: #51
- Add support global config
- Add `repopack --init --global` command to support creating global configuration files
The global configuration file will be created in:
- Windows: `%LOCALAPPDATA%\Repopack\repopack.config.json`
- macOS/Linux: `$XDG_CONFIG_HOME/repopack/repopack.config.json` or `~/.config/repopack/repopack.config.json`
Note: Local configuration (if present) takes precedence over global configuration.
We've added support for global configuration files to allow users to easily maintain common settings across multiple projects. This enhances the Repopack user experience and enables more flexible configuration management.

Add support for global configuration files

---

src/core/file/fileSearcher.ts
tests/core/file/fileSearcher.test.ts

This PR addresses a critical issue where Repopack could potentially process its own output file.

fix(ignore): Fix output file inclusion

---

src/core/file/fileManipulator.ts
src/core/file/fileProcessor.ts
tests/core/file/fileManipulator.test.ts
tests/core/file/fileProcessor.test.ts

This PR simplifies our approach to removing comments from Python files.
#55
- Only remove single-line comments starting with '#'
- Preserve all other content, including string literals and f-strings
- Do not attempt to remove docstrings or multi-line comments
This change resolves the issue with f-strings being incorrectly removed while simplifying our overall approach to comment removal.

Fix Python comment removal to preserve f-strings

---

README.md
src/cli/actions/defaultActionRunner.ts
src/cli/actions/remoteActionRunner.ts
src/cli/cliPrinter.ts
src/cli/cliRunner.ts
src/config/configLoader.ts
src/config/configTypes.ts
src/core/file/fileSearcher.ts
src/core/packager.ts
src/shared/processConcurrency.ts
tests/cli/actions/defaultActionRunner.test.ts
tests/cli/actions/remoteActionRunner.test.ts
tests/config/configLoader.test.ts
tests/integration-tests/packager.test.ts
tests/testing/testUtils.ts

This PR introduces a new feature that allows Repopack to process remote Git repositories without requiring local cloning by the user. This enhancement significantly expands the tool's capabilities and improves user experience.
- Added new `--remote` option to process remote Git repositories
Process a GitHub repository:
```bash
repopack --remote https://github.com/user/repo.git
```
Use GitHub shorthand:
```bash
repopack --remote user/repo
```
- Created new file: `src/cli/actions/remoteActionRunner.ts`
- Updated `src/cli/cliRunner.ts` to include the new `--remote` option
- Utilized `cliSpinner` for rich visual feedback during processing
- Implemented error handling for various scenarios (Git not installed, clone failure, etc.)
- Ensured proper cleanup of temporary directories
information is …

Add remote repository processing feature

---

src/cli/actions/defaultActionRunner.ts
src/cli/actions/remoteActionRunner.ts
src/cli/cliSpinner.ts
src/config/defaultIgnore.ts
src/core/packager.ts
src/core/security/securityCheckRunner.ts
src/shared/sleep.ts
src/shared/types.ts
tests/core/packager.test.ts

This PR addresses performance issues and improves the user experience by preventing the appearance of hanging during CPU-intensive operations.
Key changes:
1. Performance improvements:
- Introduced sleep() in CPU-heavy processes (security check, metrics calculation) to prevent event loop blocking
- Optimized CLI spinner for more efficient updates
2. Progress reporting enhancements:
- Implemented a progress callback system for real-time updates
- Added detailed progress messages for each stage of the packing process
3. Python support:
- Extended default ignore list with essential Python-related entries
These changes significantly improve the responsiveness of the application during long-running tasks and provide users with better visibility into the packing process.

Enhance performance and user experience with improved progress reporting

---

biome.json
package.json
src/cli/actions/initActionRunner.ts
tests/cli/actions/initActionRunner.test.ts
tsconfig.json
vite.config.ts

Key changes:
1. Separated the creation processes for repopack.config.json and .repopackignore files, allowing users more granular control over their setup.
These improvements will make it easier for new users to get started with Repopack and provide a smoother configuration experience for all users.

Enhance Repopack initialization process for better user experience

---

README.md
repopack.config.json
src/cli/actions/defaultActionRunner.ts
src/cli/cliPrinter.ts
src/config/configLoader.ts
src/config/configTypes.ts
src/config/configValidator.ts
src/config/defaultConfig.ts
src/core/packager.ts
tests/cli/actions/defaultActionRunner.test.ts
tests/core/packager.test.ts
tests/testing/testUtils.ts

This PR introduces an option to control the security check, allowing users to enable or disable the security check as needed.
related: #74
Key changes:
- Add new config option `security.enableSecurityCheck` (default is `true`)
- Update packager to conditionally run security check based on this setting
- The `security.enableSecurityCheck` option is added to the configuration schema
- When set to `false`, the packager skips the security check process
- CLI output is updated to indicate whether the security check was performed or skipped
- Default behavior (security check enabled) remains unchanged for existing users

Add option to control security check

---

src/config/configValidate.ts
tests/config/configValidate.test.ts

Running `repopack` with `output.style` set to `markdown` generates the following error:
```
Error: Invalid configuration in /path/to/repo/repopack.config.json: output.style must be either "plain" or "xml"
```

fix: Allow markdown as valid option in configuration

---

src/core/output/outputGenerate.ts
src/core/output/outputStyles/markdownStyle.ts
src/core/output/outputStyles/plainStyle.ts
src/core/output/outputStyles/xmlStyle.ts
tests/core/output/outputStyles/markdownStyle.test.ts
tests/core/output/outputStyles/plainStyle.test.ts
tests/core/output/outputStyles/xmlStyle.test.ts

This refactor fixes the duplication of renderContext and the generation process for each style while maintaining functionality. 
1. Modified `outputGenerate.ts`:
- Added a new `createRenderContext` function
- Centralized template compilation and rendering in `generateOutput` function
2. `plainStyle.ts`, `xmlStyle.ts`, and `markdownStyle.ts` now return template strings
3. Updated tests to reflect new changes:
- Modified tests function for all styles
- Ensured tests cover template structure, placeholder presence, and correct rendering
All existing tests have been updated, passed and manually tested to ensure output remains consistent with previous versions

Refactor Styles & OutputGenerate functions to streamline generation process

---

.github/workflows/brew.yml

Automatically push new updates to brew.
This will not work without the the COMMITTER_TOKEN secret. 
See https://github.com/mislav/bump-homebrew-formula-action

feat: Create brew.yml for auto-update of repopack formula

---

src/core/file/fileSearch.ts

This PR includes several updates to the `searchFiles` function and related helper functions to enhance performance, code efficiency, and error handling.
1. **Parallel Execution for Improved Performance**:
- Updated `searchFiles` to execute `getIgnorePatterns` and `getIgnoreFilePatterns` in parallel using `Promise.all`, reducing the overall execution time.
2. **Enhanced Error Handling**:
- Refined error handling in `searchFiles` by using an `if` check for `instanceof Error`. This ensures specific error messages are logged, while a generic error message is used for unexpected cases.
3. **Simplified Conditional Logic**:
- Removed the unnecessary `else` clause since the previous `if` block already throws an error. This improves readability and simplifies the control flow.
4. **Minor Code …

Improve Error Handling and Code Efficiency in `searchFiles.ts` Function

---

src/shared/processConcurrency.ts

This method returns an estimate of the default amount of parallelism a program should use, compared to `cpus().length` which returns the cpu core count.

fix(processConcurrency): improve process concurrency count

---

src/core/packager.ts
src/core/security/securityCheck.ts
src/shared/sleep.ts

```ts
const sleep = (ms: number): Promise<void> => new Promise((resolve) => setTimeout(resolve, ms));
```
This type of hack is not needed since node comes with promise based timers module which can be used as:
```ts
import { setTimeout } from 'node:timers/promises'
await setTimeout(1000)
```

fix: use async setTimeout for sleep

---

.github/workflows/ci.yml
src/cli/cliRun.ts

This PR adds a migration notice to inform users about the project's rename from Repopack to Repomix.

feat(rename): Add migration notice for repomix

---

.github/workflows/release.yml

re-add homebrew bump flow per [formula rename](https://github.com/Homebrew/homebrew-core/pull/196439).
---
using official brew actions this time so that the npmjs artifact issue would be resolved see [here](https://github.com/Homebrew/homebrew-core/pull/196454) and [here](https://github.com/Homebrew/homebrew-core/pull/196430)

feat: re-add homebrew bump flow

---

.github/workflows/ci.yml

- Add actionlint job to check workflow files syntax
- Update Ubuntu runner from ubuntu-24.04 to ubuntu-latest

chore(ci): Add actionlint

---

.github/workflows/ci.yml

🐳 Use actionlint's Docker image.

Use official actionlint image in CI

---

README.md
package-lock.json
package.json
src/cli/actions/defaultAction.ts
src/cli/cliRun.ts
src/config/configTypes.ts
src/config/defaultConfig.ts
src/core/packager.ts
tests/cli/actions/defaultAction.test.ts
tests/core/packager.test.ts

hello :) this is my first PR to an opensource tech! all crit feedback is appreciated
- implemented optional clipboard output flag
- added related test cases 
- updated pkg dependecnies to follow a [clipboard-based package](https://www.npmjs.com/package/clipboardy)
- modified config types to support new style
note: linted + tested - please test on different systems (I'm running MacOS)

feat: added copy functionality from #152

---

src/core/file/fileSearch.ts
src/core/file/permissionCheck.ts

This PR adds permission checking before scanning directories in the searchFiles function. 
related: #162

feat(file): Add permission checks for directory scanning

---

src/cli/actions/remoteAction.ts
src/core/file/gitCommand.ts
src/core/packager.ts
tests/cli/actions/remoteAction.test.ts
tests/core/file/gitCommand.test.ts
tests/core/packager.test.ts

This PR extracts git-related functionality into a dedicated core module and improves the testing approach by using dependency injection.
- Move git commands to new `core/file/gitCommand.ts`
- Add dependency injection for git commands
- Remove direct git execution in tests
- Simplify test implementation
- Added new test file for git commands
- Updated existing remote action tests to use mocked dependencies

refactor(core): Git Command Module Extraction

---

src/cli/cliPrint.ts
src/core/packager.ts
tests/core/packager.test.ts

This PR improves the readability of statistics output and fixes how total character and token counts are calculated. Previously, the totals were showing the sum of individual files rather than the metrics of the final output file.

feat(cli): Add number formatting and fix statistics calculation

---

.github/pull_request_template.md

chore(github): Add PR template

---

README.md

docs: Add codecov badge

---

repomix.config.json
src/config/configSchema.ts
src/core/file/fileSearch.ts
src/core/file/fileTreeGenerate.ts
src/core/output/outputGenerate.ts
src/core/packager.ts
tests/core/file/fileSearch.test.ts
tests/core/packager.test.ts

Added the option to include empty directory, also with the config flag <code>output.includeEmptyDirectories</code>
I also updated test cases to cover existing changes and  added new test for checking flag option
Related: #161

Implemented option to include empty directory

---

README.md

Added documentation for <code>includeEmptyDirectories</code> option to README

Added documentation for includeEmptyDirectories option to README

---

.github/workflows/ci.yml

Add production dependencies check to prevent dev dependencies leaks in v0.2.4

Add production dependencies check to prevent dev dependencies leaks

---

README.md

docs: Simplify project rename notice and add discussion link

---

src/cli/actions/remoteAction.ts
src/cli/cliRun.ts
src/core/file/gitCommand.ts
tests/core/file/gitCommand.test.ts

Draft Implementation as proposed in https://github.com/yamadashy/repomix/issues/195

Add remote branch option

---

package-lock.json

chore(deps): bump nanoid from 3.3.7 to 3.3.8

---

README.md
src/cli/actions/defaultAction.ts
src/cli/cliRun.ts
tests/cli/actions/defaultAction.test.ts
tests/cli/cliRun.test.ts

This PR adds a command line option to disable security checks, following commander.js's negatable boolean pattern.
related: #191

feat(cli): Add --no-security-check command line option

---

tests/core/metrics/aggregateMetrics.test.ts

Sorry for the mistake in my PR #217. Not really sure how I ended up importing from the distribution directory without anything failing in my branch, but it was certainly breaking CI in main.

Fix import error that was causing CI to fail

---

.github/workflows/ci.yml

Enable npm caching for faster CI

ci(cache): Use setup-node npm cache

---

README.md
biome.json
package-lock.json
package.json
repomix.config.json
src/config/configLoad.ts
tests/config/configLoad.test.ts

Integrated [strip-json-comments](https://github.com/sindresorhus/strip-json-comments) to clean JSON configuration files by removing comments before parsing.
```
stdout | tests/cli/actions/initAction.test.ts > initAction > createConfigFile > should create a new local config file when one does not exist
configPath /test/dir/repomix.config.json
✓ tests/cli/actions/migrationAction.test.ts (5)
✓ tests/core/file/permissionCheck.test.ts (13)
✓ tests/core/packager.test.ts (5)
✓ tests/cli/actions/initAction.test.ts (11)
✓ tests/config/configSchema.test.ts (14)
✓ tests/cli/cliRun.test.ts (9)
✓ tests/core/file/fileProcess.test.ts (8)
✓ tests/core/tokenCount/tokenCount.test.ts (12)
⠙ should correctly pack simple xml style
✓ tests/cli/cliPrint.test.ts (8)
✓ tests/cli/cliRun.test.ts (9)
✓ …
```

integrate strip-json-comments for JSON configuration parsing

---

src/cli/actions/remoteAction.ts
src/core/file/fileProcess.ts
src/core/packager.ts
src/core/security/runSecurityCheckIfEnabled.ts
tests/core/file/fileProcess.test.ts
tests/core/packager.test.ts
tests/core/security/runSecurityCheckIfEnabled.test.ts

Related: #208
This PR addresses the issue where the main thread hangs when processing large codebases with removeComments and removeEmptyLines enabled.

feat(process): Prevent main thread blocking in file processing

---

.github/workflows/docker.yml

ref
- https://github.com/yamadashy/repomix/pull/222#issuecomment-2565003641

ci(docker): Add release permissions to docker workflow

---

.github/dependabot.yml
.github/workflows/ci.yml

- Add dependanbot config to track updates of `GitHub Actions`.
- Remove node 16.x from `build step`.

Add dependabot, remove 16.x from build step

---

.github/workflows/docker.yml
.github/workflows/homebrew.yml

ci(docker): Add latest tag for v* release tags and modify push events

---

README.md

docs(readme): Separate docker commands for easier copy & paste

---

src/cli/actions/remoteAction.ts
src/core/file/gitCommand.ts
tests/core/file/gitCommand.test.ts

- https://github.com/yamadashy/repomix/issues/195?notification_referrer_id=NT_kwDOByTsI7UxMzc1NzczNzE5ODoxMTk4NjAyNTk
- https://github.com/yamadashy/repomix/pull/196
- https://github.com/yamadashy/repomix/pull/199
The older PR claims to support branch names, tags, and commit hashes, but commit hashes are not actually supported.

Support commit SHA in --remote-branch option

---

README.md

docs(readme): Improve remote repository usage examples

---

.github/workflows/docker.yml

https://github.com/yamadashy/repomix/issues/221#issuecomment-2565521325

ci(docker): Fix workflow trigger from tag to main branch push

---

src/core/file/fileCollect.ts
src/core/file/fileProcess.ts
src/core/security/securityCheck.ts

feat(core): Improve logging and performance of file processing

---

.github/workflows/ci.yml

ci(tests): Add version, help tests

---

.github/copilot-instructions.md
repomix-instruction.md

chore(github): Add copilot instruction

---

src/cli/actions/remoteAction.ts
src/index.ts
tests/cli/cliRun.test.ts

feat(remote): Return result from remoteAction and export actions

---

src/core/output/outputStyles/markdownStyle.ts
src/core/output/outputStyles/plainStyle.ts
src/core/output/outputStyles/xmlStyle.ts
src/index.ts

fix(template): Fix template break line

---

.npmignore
package.json

- chore(npm): Add website, .devcontainer to npmignore
- fix(package): Fix package.json exports section

chore(npm): Add website, .devcontainer to npmignore

---

README.md

docs(readme): Add announcements

---

website/client/.vitepress/theme/components/TryIt.vue
website/client/.vitepress/theme/components/api/client.ts
website/client/.vitepress/theme/components/utils/analytics.ts
website/server/src/remoteRepo.ts
website/server/src/schemas/request.ts
website/server/src/types.ts
website/server/src/utils/validation.ts

ref: https://github.com/yamadashy/repomix/issues/219#issuecomment-2570148830

feat(website): Add include patterns support to web interface

---

src/core/file/fileSearch.ts

Hi @yamadashy! 👋
I think we have an issue with ignoring the output file when a target is specified.
```bash
npx repomix foo/bar --output foo/bar/custom-output.txt
```
-> The `custom-output.txt` file is not ignored. If we run the command multiple times, it leads to an increased output file size, etc.
I believe this happens because the output file added to the `ignorePatterns` is the path `foo/bar/custom-output.txt`. 
However, `globby` compares the `rootDir` with this path. 
When a target is specified, the `rootDir` becomes `/current-working-directory/foo`. As a result, `globby` tries to ignore `/foo/bar/custom-output.txt` inside `/cwd/foo`, which it cannot find.
The ignored file needs to be relative to the target, in this case `/bar/custom-output.txt`.
We need to use a relative path to the …

fix(cli): ignore output path using a relative path to the target

---

README.md
repomix.config.json
src/cli/actions/defaultAction.ts
src/cli/cliRun.ts
src/config/configSchema.ts
src/core/metrics/calculateMetrics.ts
src/core/packager.ts
src/core/tokenCount/tokenCount.ts
tests/cli/actions/defaultAction.test.ts
tests/cli/cliRun.test.ts
tests/config/configSchema.test.ts
tests/core/metrics/calculateMetrics.test.ts
tests/core/packager.test.ts
tests/core/tokenCount/tokenCount.test.ts
tests/testing/testUtils.ts

This PR adds the ability to configure the token count encoding used by Repomix and changes the default encoding to `o200k_base`.

feat(website): Add configurable token count encoding and change default to o200k_base

---

src/cli/cliPrint.ts
tests/cli/cliPrint.test.ts

Add browser version announcement (https://repomix.com) to tool completion message.
Currently, the announcement appears every time.

feat(cli): Add browser version announcement to completion message

---

src/core/file/gitCommand.ts
tests/core/file/gitCommand.test.ts
website/client/.vitepress/theme/components/TryIt.vue
website/client/.vitepress/theme/components/api/client.ts

feat(remote): Replace exec with execFile for improved security

---

README.md

docs(readme): add Gitingest as an alternative tool for Python users

---

src/cli/actions/remoteAction.ts
src/core/file/gitCommand.ts
src/index.ts
tests/cli/actions/remoteAction.test.ts

Improve repository URL validation logic and expose it for website use. Update validation patterns to strictly follow GitHub's repository name rules.
related: #278

feat: enhance repository name validation and expose validation function

---

src/core/file/fileSearch.ts
tests/core/file/fileSearch.test.ts

Fixes an issue where Repomix fails when processing repositories created using `git worktree`. The error occurred because in worktree repositories, `.git` is a file containing a reference to the main repository, rather than a directory:
```
❯ repomix
📦 Repomix v0.2.17
Error filtering files: ENOTDIR: not a directory, stat '/Users/shvets/repos/testrepo_worktree/.git/**'
✖ Error during packing
Unexpected error: Failed to filter files in directory /Users/shvets/repos/testrepo_worktree. Reason: ENOTDIR: not a directory, stat '/Users/shvets/repos/testrepo_worktree/.git/**'
For more help, please visit: https://github.com/yamadashy/repomix/issues
```
- Added detection of git worktree reference files
- Modified ignore patterns to handle `.git` file instead of `.git/**` directory for worktrees
- …

Git Worktree Support

---

.github/workflows/ci.yml
website/client/.vitepress/config/configEs.ts
website/client/.vitepress/config/configJa.ts
website/client/.vitepress/config/configKo.ts
website/client/.vitepress/config/configPtBr.ts
website/client/.vitepress/config/configShard.ts
website/client/.vitepress/config/configZhCn.ts

refactor(website): Separate search translations for each language into separate files

---

README.md
website/client/src/en/guide/installation.md
website/client/src/en/index.md
website/client/src/es/guide/installation.md
website/client/src/es/index.md
website/client/src/ja/guide/installation.md
website/client/src/ja/index.md
website/client/src/ko/guide/installation.md
website/client/src/ko/index.md
website/client/src/pt-br/guide/installation.md
website/client/src/pt-br/index.md
website/client/src/zh-cn/guide/installation.md
website/client/src/zh-cn/index.md

- homebrew also supports linux, update the readme to reflect it.

chore: update brew installation note

---

README.md
package-lock.json
package.json
src/cli/actions/defaultAction.ts
src/cli/cliRun.ts
src/config/configSchema.ts
src/core/output/outputGenerate.ts
src/core/output/outputStyles/markdownStyle.ts
tests/cli/actions/defaultAction.test.ts
tests/cli/cliRun.test.ts
tests/config/configSchema.test.ts
tests/core/output/outputGenerate.test.ts
website/server/src/remoteRepo.ts
website/server/src/schemas/request.ts
website/server/src/types.ts

See #282 
Adds a `parsableStyle` flag to ensure the output strictly follows the specification of the output style.

XML Escaping

---

src/core/file/fileCollect.ts
tests/core/file/fileCollect.test.ts

Fixes critical out-of-memory errors when processing repositories containing large files
When accidentally adding a large file to a repository (such as a 480MB txt file), Repomix would try to load it into memory and crash with a Node.js heap out-of-memory error:
```
❯ repomix
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
[1]    63614 abort      repomix
```
This provides a poor user experience as:
1. The error is not user-friendly or actionable
2. The program crashes instead of gracefully handling the situation
3. Users don't know which file caused the problem
Added a size limit check (50MB) before loading files into memory, with clear user guidance:
```
📦 Repomix v0.2.21
⚠️ Large File Warning: …
```

Handle large files gracefully

---

src/config/defaultIgnore.ts

This PR adds Rust-specific patterns to the default ignore list.

feat(ignore): Add Rust default ignores

---

README.md
package-lock.json
package.json
src/cli/actions/remoteAction.ts
tests/cli/actions/remoteAction.test.ts

This PR helps resolving https://github.com/yamadashy/repomix/issues/311, adding the ability to parse the cli option value --remote (remote repository url) to get branch/commit/tag.
**This PR does not modify any code of the website.**
For example:
```
npm run repomix -- --remote https://github.com/yamadashy/repomix/tree/0.1.x
```
Works exactly the same as:
```
npm run repomix -- --remote https://github.com/yamadashy/repomix --remote-branch 0.1.x
```
New dependency: 
-  "git-url-parse": "^16.0.0"
-  "@types/git-url-parse": "^9.0.3"

Support getting remote ref by parsing url

---

.github/copilot-instructions.md
repomix-instruction.md

chore: update release note section in repomix-instruction.md

---

website/client/src/en/index.md
website/client/src/es/index.md
website/client/src/ja/index.md
website/client/src/ko/index.md
website/client/src/pt-br/index.md
website/client/src/zh-cn/index.md
website/server/package-lock.json
website/server/package.json

feat(website): Add support for parsing git URLs

---

src/cli/actions/defaultAction.ts
src/cli/actions/remoteAction.ts
src/cli/cliRun.ts
src/core/output/outputGenerate.ts
src/core/packager.ts
tests/cli/actions/defaultAction.test.ts
tests/cli/cliRun.test.ts
tests/core/output/outputGenerate.test.ts
tests/core/output/outputStyles/plainStyle.test.ts
tests/core/output/outputStyles/xmlStyle.test.ts
tests/core/packager.test.ts
tests/integration-tests/packager.test.ts

On large projects, I will have files that are contextually related but in separate sub directories that I would like to bundle together. However, due to token limits, I don't necessarily want to find the closest common parent directory and bundle the entire thing. What I really wanted was an option to be able to pass in multiple directories as arguments and have repomix bundle them all together automatically, something like
```
repomix path/to/foo path/to/bar ...
```
This PR adds support for having the `directory` argument be an arbitrary number of directories instead of a single string and collects all of that into one output. 
```
➜  repomix git:(rc/multiple-dir-paths) npm run repomix src/cli src/core
```
yields 
```
➜  repomix git:(rc/multiple-dir-paths) cat repomix-output.xml | rg -U …
```

Allow for passing in multiple directories

---

README.md
website/client/src/de/guide/index.md
website/client/src/en/guide/index.md
website/client/src/es/guide/index.md
website/client/src/ja/guide/index.md
website/client/src/ko/guide/index.md
website/client/src/pt-br/guide/index.md
website/client/src/zh-cn/guide/index.md

Fixed inconsistencies in the model list to include all the models listed at the top of the readme.
I didn't do either since it is a readme change.

Fixed inconsistencies in model lists

---

website/client/.vitepress/config/configDe.ts
website/client/.vitepress/config/configEnUs.ts
website/client/.vitepress/config/configEs.ts
website/client/.vitepress/config/configJa.ts
website/client/.vitepress/config/configKo.ts
website/client/.vitepress/config/configPtBr.ts
website/client/.vitepress/config/configZhCn.ts
website/client/src/de/guide/code-compress.md
website/client/src/de/guide/command-line-options.md
website/client/src/de/guide/configuration.md
website/client/src/en/guide/code-compress.md
website/client/src/en/guide/command-line-options.md
website/client/src/en/guide/configuration.md
website/client/src/en/guide/usage.md
website/client/src/es/guide/code-compress.md
website/client/src/es/guide/command-line-options.md
website/client/src/es/guide/configuration.md
website/client/src/ja/guide/code-compress.md
website/client/src/ja/guide/command-line-options.md
website/client/src/ja/guide/configuration.md
website/client/src/ja/guide/usage.md
website/client/src/ko/guide/code-compress.md
website/client/src/ko/guide/command-line-options.md
website/client/src/ko/guide/configuration.md
website/client/src/pt-br/guide/code-compress.md
website/client/src/pt-br/guide/command-line-options.md
website/client/src/pt-br/guide/configuration.md
website/client/src/zh-cn/guide/code-compress.md
website/client/src/zh-cn/guide/command-line-options.md
website/client/src/zh-cn/guide/configuration.md

ref
- https://github.com/yamadashy/repomix/pull/336

docs(website): Code Compression docs

---

website/client/.vitepress/theme/custom.css
website/client/components/PackButton.vue
website/client/components/TryIt.vue
website/client/components/TryItFileUpload.vue
website/client/components/TryItUrlInput.vue
website/client/components/api/client.ts
website/client/components/utils/requestHandlers.ts
website/server/package-lock.json
website/server/package.json
website/server/src/constants.ts
website/server/src/index.ts
website/server/src/processZipFile.ts
website/server/src/remoteRepo.ts
website/server/src/schemas/request.ts
website/server/src/utils/cache.ts
website/server/src/utils/fileUtils.ts
website/server/src/utils/sharedInstance.ts

First of all @yamadashy , your repo is neat and clean, its easy to run with docker. Great work. Here are my changes. (you check this also: https://youtu.be/VjBGvu9cECo)
Issue link: https://github.com/yamadashy/repomix/issues/310
Changes done:
Client:
- added TryItFileUpload.vue
- moved the shared button to PackButton.vue
- shifted the pack button below the url input field or zip upload box.
Server:
- added processZipFile.ts and fileUtils.ts
- added adm-zip package
- changed zod schema for validation of both url and file
- remoteRepo.ts and processZipFile.ts both share the same instance of ratelimiter and cache
Way forward:
I didn't implement folder uploading. We can create a separate ticket for that.
Ping me if you have any suggestions.

Added zip file upload feature

---

.github/workflows/ci.yml
website/client/components/TryIt.vue
website/client/components/TryItFileUpload.vue
website/server/package-lock.json

fix(website): Fix some UI dark mode issues

---

website/compose.yml
website/server/package-lock.json
website/server/package.json
website/server/src/index.ts
website/server/src/processZipFile.ts
website/server/src/remoteRepo.ts
website/server/src/utils/logger.ts
website/server/src/utils/network.ts

feat(website): Run repomix in quiet mode on the website

---

README.md
biome.json
package-lock.json
package.json
repomix.config.json
src/config/configLoad.ts
tests/config/configLoad.test.ts

Closes #346
This PR adds support for JSON5 in configuration files, allowing for a more flexible and developer-friendly configuration experience.
- Replace JSON.parse with JSON5.parse for configuration file loading
- Update tests to cover JSON5 features (comments, trailing commas)
- Update documentation to reflect JSON5 support
- Add json5 package as a dependency
- Added new test cases specifically for JSON5 features
- Tested with configuration files containing comments and trailing commas
- Verified backward compatibility with standard JSON
- Updated README.md to document JSON5 support and features
- Added example configuration using JSON5 syntax

feat: Add support for JSON5 in configuration files

---

.clinerules
.github/copilot-instructions.md
.gitignore
repomix-instruction.md

chore: Update instructions

---

src/cli/actions/remoteAction.ts
src/core/packager/writeOutputToDisk.ts
tests/cli/actions/remoteAction.test.ts

When using nested output paths (e.g. `--output docs/nested/file.xml`), the tool fails because parent directories are not automatically created. This PR fixes the issue by ensuring folders exist before writing files.
related: #378

fix(remote): ensure output directories exist before file writing

---

src/cli/actions/defaultAction.ts
tests/cli/actions/defaultAction.test.ts

related: #385
- Issue #385 reported that setting `"fileSummary": false` in the config file doesn't work
- The file summary still appeared in the output despite the config setting
- Investigation showed this affects all `--no-*` style CLI options
- Commander.js sets options to `true` by default when not specified
- Our code was applying settings whenever `options.xyz !== undefined`
- This meant config file settings weren't being respected because CLI options always had a value

fix(option): properly handle "false" config values for --no-* options

---

src/core/file/fileSearch.ts
tests/core/file/fileSearch.test.ts

Use the contents of .git/info/exclude when useGitignore is set to true. Fixes #375

---

website/server/src/schemas/request.ts

Allow `!` `(` and `)` in ignorePatterns submitted via the website.
These are useful if you want to have a pattern like `!.(cursor)/**` which ignores all dot-prefixed folders in the root *except* `.cursor/`.
you can manually test that negations `!` and parentheses `()` are not just valid but useful in the ignorePattern using this script:
```
#!/bin/bash
set -e
echo "📁 Creating test directory structure..."
TEST_DIR="repomix-test"
mkdir -p "$TEST_DIR"
cd "$TEST_DIR"
echo "📝 Creating test files..."
mkdir -p .hidden .cursor .git
echo "Hidden file content" > .hidden/file.txt
echo "Cursor file content" > .cursor/file.txt
echo "Git file content" > .git/file.txt
echo "Regular file content" > regular.txt
echo "⚙️ Creating repomix configuration..."
cat > repomix.config.json << 'EOF'
{
"output": { …
```

allow ! ( and ) in ignorePatterns via website

---

src/cli/actions/mcpAction.ts
src/core/security/workers/securityCheckWorker.ts
src/mcp/mcpServer.ts
src/mcp/prompts/packRemoteRepositoryPrompts.ts
src/mcp/tools/fileSystemReadDirectoryTool.ts
src/mcp/tools/fileSystemReadFileTool.ts
src/mcp/tools/mcpToolRuntime.ts
src/mcp/tools/packCodebaseTool.ts
src/mcp/tools/packRemoteRepositoryTool.ts
src/mcp/tools/readRepomixOutputTool.ts

feat(mcp): Added the ability to read files and directories to MCP. Files that are read are checked by Secretlint.

---

src/core/file/fileManipulate.ts
tests/core/file/fileManipulate.test.ts

- Add support for .h, .hpp, .cpp, .cc, and .cxx file extensions
- Configure all C++ extensions to use the existing C comment stripper
- Add comprehensive test cases for each supported C++ extension
- Verify correct handling of various comment styles in each file type
This enhancement improves code processing capabilities for C++ projects.

feat(file): add C++ file extensions support for comment stripping

---

website/client/src/de/guide/command-line-options.md
website/client/src/en/guide/command-line-options.md
website/client/src/es/guide/command-line-options.md
website/client/src/fr/guide/command-line-options.md
website/client/src/ja/guide/command-line-options.md
website/client/src/ja/index.md
website/client/src/ko/guide/command-line-options.md
website/client/src/pt-br/guide/command-line-options.md
website/client/src/zh-cn/guide/command-line-options.md

いつのタイミングか標準outputがxmlになったようですが
一部ドキュメントがtextのままだったので修正しました

Fix missing doc update for default switch to XML

---

src/cli/actions/defaultAction.ts
tests/cli/actions/defaultAction.test.ts

Fixes an issue where whitespace after commas in CLI pattern arguments wasn't being trimmed, causing unexpected behavior with ignore patterns. Users can now write more readable comma-separated patterns with spaces (e.g., --ignore "pattern1,  pattern2") and have them correctly parsed, improving usability and making the CLI behavior more intuitive.

Trim whitespace in comma-separated glob patterns

---

src/core/file/fileSearch.ts
tests/core/file/fileSearch.test.ts

This PR fixes an issue where ignore patterns with different formats (**/folder, **/folder/, and **/folder/**/*) weren't being handled consistently.
Changes
- Enhanced normalizeGlobPattern function to convert **/folder patterns to **/folder/**
- This ensures all variants of directory exclusion patterns work identically
- Added tests to verify the consistent behavior across different pattern formats
Problem Solved
Users previously had to know the exact pattern format to use for ignoring directories. Now all three common formats work as expected, improving usability when excluding directories with patterns like:
- `--ignore "**/bin"`
- `--ignore "**/bin/"`
- `--ignore "**/bin/**/*"`

Consistent handling of directory patterns with trailing slashes in glob patterns

---

src/cli/actions/defaultAction.ts
src/core/file/fileSearch.ts
src/shared/patternUtils.ts
tests/core/file/fileSearch.test.ts
tests/shared/patternUtils.test.ts

Issue
The CLI --include and --ignore options had two issues with pattern handling:
- Brace expansion patterns like **/{__tests__,theme}/** were incorrectly split at the comma inside braces, resulting in broken patterns ["**/{__tests__", "theme}/**"]
- Whitespace in patterns like **/__tests__/**, **/theme/** was preserved, causing unexpected behavior with leading/trailing spaces
Solution
- Added a new splitPatterns utility function that tracks brace nesting level to preserve brace expansion patterns
- Enhanced pattern handling to trim whitespace from each pattern
- Added comprehensive tests for both behaviors
Before :
```
"**/{__tests__,theme}/**" → ["**/{__tests__", "theme}/**"] // Incorrectly split brace pattern
"**/__tests__/**, **/theme/**" → ["**/__tests__/**", " **/theme/**"] // Note …
```

Fix brace expansion and whitespace in CLI pattern options

---

src/core/packager/copyToClipboardIfEnabled.ts

Add Wayland copy support; `repomix --copy` does not copy anything when on a Wayland compositor as clipboardy package is stale.

feat: add wl-copy support

---

src/core/packager.ts
src/index.ts
tests/core/packager.test.ts
tests/integration-tests/packager.test.ts

Hey @yamadashy,
Looks like you've already added some of the functions I wanted to export. Here's the summary of changes:
1. Allow overriding default deps without needing to import other dependencies
2. Rename `writeOutputToDisk` to `handleOutput` with `writeOutputToDisk` as default
3. Export `generateFileTree` function from package

feat(core): Make it easier to pick & override pack's deps + core export

---

src/mcp/tools/readRepomixOutputTool.ts

Changed the response type of the MCP tool (`readRepomixOutputTool`) from `resource` to `text`.
related:
- https://github.com/yamadashy/repomix/issues/472
In the Cursor environment, MCP tool responses of type `resource` are not properly recognized or displayed. To ensure compatibility and correct display, the response is now returned as `text`.

fix(mcp): Change readRepomixOutputTool response from resource to text

---

.github/instructions/website.instructions.md
website/client/components/Home/TryIt.vue
website/client/components/Home/TryItUrlInput.vue

This PR adds browser history feature to the URL input field in Try It section of the website. 
Features added:
- Save GitHub repository URLs to browser history
- Custom dropdown for managing URL history
- Ability to delete individual history entries
- Option to clear all history
- Improved UX with hover effects and clear UI
This enhancement makes it easier for users to access their previously used repository URLs without having to remember or retype them.

Add URL input history with management features

---

.github/instructions/base.instructions.md
.gitignore
src/cli/cliPrint.ts
website/client/components/Home/TryItResultContent.vue
website/client/components/Home/TryItUrlInput.vue

Introduce guidelines for pull requests to improve contribution clarity. Update `.gitignore` to include rules for private files and refine existing ignore patterns. Enhance the CLI output to display the percentage of total tokens for top files, providing better insights into token distribution.

Add pull request guidelines, update .gitignore, and enhance CLI output

---

README.md
src/cli/actions/defaultAction.ts
src/cli/cliRun.ts
src/cli/cliSpinner.ts
src/cli/types.ts
src/config/configSchema.ts
src/core/packager/writeOutputToDisk.ts
src/index.ts
tests/cli/actions/defaultAction.test.ts
tests/cli/cliRun.test.ts
tests/core/packager/writeOutputToDisk.test.ts
tests/core/treeSitter/parseFile.solidity.test.ts
tests/mcp/tools/packCodebaseTool.test.ts
website/client/src/de/guide/command-line-options.md
website/client/src/en/guide/command-line-options.md
website/client/src/es/guide/command-line-options.md
website/client/src/fr/guide/command-line-options.md
website/client/src/ja/guide/command-line-options.md
website/client/src/ko/guide/command-line-options.md
website/client/src/pt-br/guide/command-line-options.md
website/client/src/zh-cn/guide/command-line-options.md
website/client/src/zh-tw/guide/command-line-options.md

Introduce a `--stdout` flag to enhance CLI flexibility by allowing output to standard output instead of a file. Update CLI configuration, documentation, and tests to support this new feature. Ensure compatibility with existing output options.

Add --stdout option for CLI output

---

src/core/output/outputGenerate.ts
src/core/output/outputStyles/markdownStyle.ts
src/core/output/outputStyles/plainStyle.ts
src/core/output/outputStyles/xmlStyle.ts
tests/core/output/outputGenerate.test.ts
tests/core/output/outputStyles/markdownStyle.test.ts
tests/core/output/outputStyles/plainStyle.test.ts
tests/core/output/outputStyles/xmlStyle.test.ts
tests/integration-tests/fixtures/packager/outputs/simple-project-output.md
tests/integration-tests/fixtures/packager/outputs/simple-project-output.txt
tests/integration-tests/fixtures/packager/outputs/simple-project-output.xml
tests/integration-tests/packager.test.ts

--no-file-summary should also suppress generationHeader; should not suppress user-specified headerText ( fixes #554 )

feat: --no-file-summary now also suppresses generationHeader; doesn't suppress headerText (fixes #554)

---

src/cli/actions/remoteAction.ts
src/core/git/gitCommand.ts
src/core/git/gitRemoteParse.ts
src/types/git-url-parse.d.ts
tests/cli/actions/remoteAction.test.ts
tests/core/git/gitCommand.test.ts
tests/core/git/gitRemoteParse.test.ts

 Proper remote‐refs handling

---

src/mcp/tools/fileSystemReadDirectoryTool.ts
src/mcp/tools/fileSystemReadFileTool.ts
src/mcp/tools/grepRepomixOutputTool.ts
src/mcp/tools/mcpToolRuntime.ts
src/mcp/tools/packCodebaseTool.ts
src/mcp/tools/packRemoteRepositoryTool.ts
src/mcp/tools/readRepomixOutputTool.ts
tests/mcp/tools/grepRepomixOutputTool.test.ts
tests/mcp/tools/mcpToolRuntime.test.ts
tests/mcp/tools/packCodebaseTool.test.ts
tests/mcp/tools/readRepomixOutputTool.test.ts

Introduce `buildMcpToolSuccessResponse` and `buildMcpToolErrorResponse` functions to standardize the creation of success and error responses across the MCP tools. This change enhances type safety and improves code readability.

Refactor MCP tool response handling for consistency

---

website/client/components/HomeBadges.vue

Correct the link to the GitHub stars in the HomeBadges component to point directly to the repository.

Update GitHub stars link in HomeBadges component

---

src/cli/cliRun.ts
tests/cli/cliRun.test.ts

Hello! Thank you for this great tool.
I noticed that repomix returns exit code 0 even when it fails with errors.
```console
$ repomix --config /dev/zero; echo $?
✖ Config file not found at /dev/zero
Need help?
• File an issue on GitHub: https://github.com/yamadashy/repomix/issues
• Join our Discord community: https://discord.gg/wNYzTwZFku
0
```
It would be helpful to be able to detect error exit when using repomix in scripts.
- Modified `src/cli/cliRun.ts` to call `process.exit(1)` when errors occur in the `run()` function

feat(cli): Set exit code when repomix fails

---

website/server/Dockerfile

Fixes the /tmp directory access permission issue when running Repomix server in Docker container with non-root user (nodejs). Changes: Removed non-root user creation and simplified to run as root user. Repomix requires write access to /tmp directory for remote repository processing and temporary file creation.

fix(docker): Use root user to resolve /tmp directory access issue

---

package-lock.json
package.json

strip-json-commentsは下記PRで使われなくなった
https://github.com/yamadashy/repomix/pull/366/files
https://github.com/search?q=repo%3Ayamadashy%2Frepomix%20%20strip-json-comments&type=code

refactor(cli) remove unused dep

---

README.md
src/cli/actions/defaultAction.ts
src/cli/cliRun.ts
src/core/file/fileStdin.ts
website/client/src/de/guide/usage.md
website/client/src/en/guide/usage.md
website/client/src/es/guide/usage.md
website/client/src/fr/guide/usage.md
website/client/src/hi/guide/usage.md
website/client/src/id/guide/usage.md
website/client/src/ja/guide/usage.md
website/client/src/ko/guide/usage.md
website/client/src/pt-br/guide/usage.md
website/client/src/vi/guide/usage.md
website/client/src/zh-cn/guide/usage.md
website/client/src/zh-tw/guide/usage.md

This PR improves stdin EOF handling and adds examples for modern file search tools (ripgrep and fd) to better support interactive tools like fzf.
**Implementation improvements:**
- Improved EOF handling in `fileStdin.ts` with proper resource cleanup using try/finally
- Enhanced code comments to explain version header suppression in stdin mode for interactive tools
- Maintained backward compatibility with existing tests
**Documentation updates:**
- Added ripgrep (`rg --files --type ts`) examples to README and website docs
- Added fd (`fd -e ts`) examples as modern find alternative
- Updated all 11 language versions of website documentation
- The `for await` loop naturally waits for EOF completion, ensuring reliable handling of piped input
- Added safe resource cleanup in finally block to …

Improve stdin EOF handling and add modern file search examples

---

.clinerules
.cursorrules
.github/copilot-instructions.md
CLAUDE.md

Consolidate AI assistant rules configuration by centralizing all rules in `.agents/rules/base.md` and removing legacy rule files.
- **Removed legacy rule files**: Deleted `.clinerules` and `.cursorrules` files that contained outdated or redundant configurations
- **Updated CLAUDE.md**: Converted from a regular file to a symlink pointing to `.agents/rules/base.md` for centralized rule management
- **Added GitHub Copilot integration**: Created `.github/copilot-instructions.md` as a symlink to the centralized rules file
This change improves maintainability by having a single source of truth for AI assistant rules while ensuring compatibility with different AI tools (Claude Code, GitHub Copilot, Cursor, etc.).

chore(config): consolidate AI assistant rules configuration

---

src/core/git/gitCommand.ts
tests/core/git/gitCommand.test.ts

I see you are trying to validate the URL by checking for hostile options.
`--` prevents subsequent arguments to be interpreted as options.

Secure gitCommand

---

README.md
website/client/components/Home/TryItResult.vue
website/client/src/de/guide/sponsors.md
website/client/src/en/guide/sponsors.md
website/client/src/es/guide/sponsors.md
website/client/src/fr/guide/sponsors.md
website/client/src/hi/guide/sponsors.md
website/client/src/id/guide/sponsors.md
website/client/src/ja/guide/sponsors.md
website/client/src/ko/guide/sponsors.md
website/client/src/pt-br/guide/sponsors.md
website/client/src/vi/guide/sponsors.md
website/client/src/zh-cn/guide/sponsors.md
website/client/src/zh-tw/guide/sponsors.md

This PR updates the Warp sponsorship content across all website files and README as requested by Warp for their partnership renewal.
- **Updated sponsor image**: Switched from local image to official Warp brand assets from GitHub (`Warp-Github-LG-01.png`)
- **Updated all links**: Changed from `www.warp.dev/repomix` to `go.warp.dev/repomix` for performance tracking
- **Updated tagline**: Changed to "Warp, built for coding with multiple AI agents" as requested
- **Applied across all languages**: Updated 12 language versions with appropriate translations
- `README.md`
- `website/client/components/Home/TryItResult.vue`
- All 12 language versions in `website/client/src/*/guide/sponsors.md`
Warp is renewing their 3-month sponsorship at $600/month and requested these updates to align with their …

feat(website): Update Warp sponsorship assets and links

---

.claude/agents/lint-fixer.md

Add Claude Code agent configuration for automated linting and fixing. This agent specializes in identifying and resolving linting issues in the codebase while maintaining code quality and project standards.
- Added `.claude/agents/lint-fixer.md` with comprehensive agent configuration
- Agent provides workflow for running `npm run lint` and systematically fixing issues
- Includes context gathering, strategic fixing approach, and verification steps
- Follows project guidelines including Airbnb JavaScript Style Guide and English-only comments
- Prioritizes fixes by severity (critical errors → style violations → formatting)
- Preserves code functionality and intent while improving quality
- Maintains consistency with existing codebase patterns
- Includes safety checks and verification steps

chore(agents): Add lint-fixer agent configuration

---

browser/package-lock.json
browser/package.json
package-lock.json
package.json
website/client/package-lock.json
website/client/package.json
website/client/tsconfig.json
website/server/package-lock.json
website/server/package.json

This PR replaces `tsc` with `tsgo` for TypeScript type checking in all subprojects to align with the main package.json configuration and improve type checking performance.
- **browser/package.json**: Updated `lint-tsc` script from `tsc --noEmit` to `tsgo --noEmit`
- **website/client/package.json**: Updated `lint-tsc` script from `tsc --noEmit` to `tsgo --noEmit`  
- **website/server/package.json**: Updated `lint-tsc` script from `tsc --noEmit` to `tsgo --noEmit`
- **All subprojects**: Added `@typescript/native-preview` dependency required for tsgo compatibility
- Consistent tooling across all packages in the monorepo
- Faster TypeScript type checking with tsgo's native performance improvements
- Reduced maintenance overhead by using the same type checking approach everywhere

Replace tsc with tsgo for type checking in subprojects

---

src/core/git/gitHubArchiveApi.ts
tests/core/git/gitHubArchive.test.ts
tests/core/git/gitHubArchiveApi.test.ts

This PR replaces hardcoded 'main' branch references with 'HEAD' in GitHub archive functionality, making the system automatically use the repository's default branch regardless of whether it's 'main', 'master', or a custom branch name.
- Replace hardcoded 'main' branch with 'HEAD' in `buildGitHubArchiveUrl` function
- Update `getArchiveFilename` to default to 'HEAD' instead of 'main'  
- Update corresponding tests to reflect the new behavior
- Eliminates compatibility issues with repositories using different default branch names
- **Better compatibility**: Works with repositories using 'master', 'main', or custom default branches
- **Future-proof**: No need to update code when GitHub or repositories change default branch naming conventions
- **Simplified logic**: Relies on GitHub's native …

feat(git): Use HEAD instead of hardcoded main branch for GitHub archives

---

.github/renovate.json5

Add `minimumReleaseAge: "7 days"` to the Renovate configuration to enhance security by introducing a waiting period before automatically updating dependencies.
This change ensures that newly released packages have time for potential security issues to be discovered and reported before being automatically adopted in our project.
- Added `minimumReleaseAge: "7 days"` to `.github/renovate.json5`
- This applies to all dependency updates managed by Renovate
- **Security**: Reduces risk of immediately adopting packages with undiscovered vulnerabilities
- **Stability**: Allows community feedback and bug reports to surface before updates
- **Best Practice**: Follows security-conscious dependency management practices

chore(config): Add minimum release age to Renovate config for security

---

src/mcp/tools/mcpToolRuntime.ts
tests/mcp/tools/fileSystemReadDirectoryTool.test.ts
tests/mcp/tools/fileSystemReadFileTool.test.ts
tests/mcp/tools/mcpToolRuntime.test.ts

This pull request makes a small change to the `buildMcpToolErrorResponse` function in `mcpToolRuntime.ts`, removing the unnecessary inclusion of the `structuredContent` property from the returned object.
Fix https://github.com/yamadashy/repomix/issues/833

fix(mcp): remove redundant structuredContent from error response

---

.agents/commands/git/release-note-generate.md
website/client/src/public/schemas/1.5.0/schema.json

Add comprehensive guidelines for writing consistent Repomix release notes based on analysis of existing releases in `.github/releases/`.
This documentation provides:
- Structured format and section guidelines
- Writing style and tone recommendations  
- Code example patterns
- Quality checklist for consistency
- Emphasis on avoiding Internal Changes sections unless user-relevant
The guidelines will help maintain consistency across future release notes and ensure they follow established patterns that emphasize user benefits and AI analysis improvements.

docs(agents): add comprehensive release note writing guidelines

---

src/cli/cliReport.ts

This PR adds token count display for git logs in the CLI summary report, providing consistency with the existing git diffs token count display.
- Add token count display for git logs in `reportSummary` function
- Display format: "✔ Git logs included (X tokens)" when logs are included
- Display format: "✖ No git logs included" when logs are not included  
- Only shows when `config.output.git?.includeLogs` is enabled
- Maintains consistency with existing git diffs display format

feat(cli): add token count display for git logs

---

browser/package-lock.json
browser/package.json
scripts/memory/package-lock.json
scripts/memory/package.json
website/client/package-lock.json
website/client/package.json
website/client/src/public/schemas/1.6.0/schema.json
website/server/package-lock.json
website/server/package.json
website/server/src/utils/validation.ts

This PR updates various dependencies across the website components and resolves compatibility issues with Zod v4.
- **Website dependencies**: Updated repomix dependency to v1.6.0 across all website packages
- **Development dependencies**: Updated @types/node, TypeScript, jsdom, and other dev dependencies to latest versions
- **Zod v4 compatibility**: Fixed validation.ts to use new Zod v4 API (`error.issues` instead of `error.errors`)
- **Dependency alignment**: Aligned @types/node versions across all packages in the monorepo
- Updated @types/node from 24.0.14 → 24.5.2
- Updated jsdom from 26.1.0 → 27.0.0
- Updated tsx from 4.20.3 → 4.20.5
- Updated TypeScript from 5.8.3 → 5.9.2
- Updated @types/node from 24.0.14 → 24.5.2
- Updated lucide-vue-next from 0.525.0 → 0.544.0
- Updated …

chore(website): update dependencies and fix Zod v4 compatibility

---

package-lock.json
package.json

Updates multiple development dependencies to their latest versions:
- **@types/node**: ^22.14.1 → ^24.5.2
- **@vitest/coverage-v8**: ^3.1.1 → ^3.2.4  
- **oxlint**: ^1.12.0 → ^1.16.0
- **tsx**: ^4.19.4 → ^4.20.5
- **typescript**: ^5.8.3 → ^5.9.2
- **vite**: ^5.4.18 → ^7.1.6
- **vitest**: ^3.1.1 → ^3.2.4
This update includes improvements in build tooling, testing infrastructure, and TypeScript support.

chore(deps): update development dependencies

---

package-lock.json
package.json
src/core/treeSitter/languageParser.ts
src/core/treeSitter/loadLanguage.ts
src/core/treeSitter/parseFile.ts
src/core/treeSitter/parseStrategies/CssParseStrategy.ts
src/core/treeSitter/parseStrategies/DefaultParseStrategy.ts
src/core/treeSitter/parseStrategies/GoParseStrategy.ts
src/core/treeSitter/parseStrategies/ParseStrategy.ts
src/core/treeSitter/parseStrategies/PythonParseStrategy.ts
src/core/treeSitter/parseStrategies/TypeScriptParseStrategy.ts
src/core/treeSitter/parseStrategies/VueParseStrategy.ts
tests/core/treeSitter/loadLanguage.test.ts
tests/core/treeSitter/parseFile.typescript.test.ts

Update web-tree-sitter to the latest version (0.25.10) to benefit from bug fixes and improvements in WASM compilation, web bindings, and performance.
- Updated `web-tree-sitter` from 0.24.7 to 0.25.10
- Adapted code to breaking API changes:
- `Parser` changed from namespace to class
- `Query` now instantiated with `new Query(language, source)` instead of `language.query(source)`
- `SyntaxNode` type renamed to `Node`
- Added null check for `Parser.parse()` return value
- Updated `TreeCursor` and `Tree` interface signatures in tests

chore(core): Update web-tree-sitter from 0.24.7 to 0.25.10
