README.md, src/cli/cliOutput.ts, src/cli/index.ts, src/core/packager.ts, src/utils/secretLintUtils.ts, tests/utils/secretLintUtils.test.ts
=> feat(output): Improve security check output

README.md, repopack.config.json, src/cli/index.ts, src/config/defaultConfig.ts, src/core/outputGenerator.ts, src/types/index.ts, tests/core/outputGenerator.test.ts, tests/core/packager.test.ts, tests/utils/fileHandler.test.ts
=> feat(output): Added option to show line numbers

src/cli/cliOutput.ts, src/core/packager.ts
Improves security by preventing potentially sensitive information from being included in the output
- Filter out suspicious files before generating output
=> Exclude suspicious files from output and update security check messaging

package-lock.json, package.json, src/core/file/fileCollector.ts, src/core/file/fileProcessor.ts, src/core/packager.ts, src/core/security/securityCheckRunner.ts, tests/core/file/fileProcessor.test.ts
This PR introduces parallel processing to improve performance in Repopack, particularly for large repositories.
Key changes:
1. Refactor fileCollector, fileProcessor, packager, and securityCheckRunner to use parallel processing
2. Use os.cpus().length to determine optimal concurrency
Benefits:
- Improved performance for processing large numbers of files
- Better utilization of system resources
=> Implement parallel processing

.codecov.yml, .github/workflows/test.yml
This PR introduces Codecov integration to our CI/CD pipeline, enhancing our ability to track and visualize code coverage across the project. It also adds a custom Codecov configuration to tailor the tool's behavior to our project's needs.
=> Add Codecov Integration and Configuration

README.md
Fixed the broken link of LICENSE in README.
This PR fixes #140
=> Broken link of LICENSE fixed in README

package-lock.json, package.json
=> fix(deps): Install minimatch

src/core/output/outputGenerate.ts
fix(instruction): use current working directory for instruction file path
=> fix(instruction): use current working directory for instruction file path

website/client/.vitepress/config.mts
=> feat(website): Swap navigation link positions for better visibility

website/client/.vitepress/theme/components/TryIt.vue
=> fix(website): Fix pack button align

README.md
=> docs(readme): Remove rename note

website/client/.vitepress/theme/components/TryIt.vue, website/client/.vitepress/theme/components/api/client.ts, website/server/src/schemas/request.ts
=> feat(website): Add support gist

website/client/.vitepress/config.mts, website/client/guide/command-line-options.md, website/client/guide/configuration.md, website/client/guide/development/index.md, website/client/guide/development/setup.md, website/client/guide/index.md, website/client/guide/installation.md, website/client/guide/output.md, website/client/guide/prompt-examples.md, website/client/guide/remote-repository-processing.md, website/client/guide/security.md, website/client/guide/usage.md
=> feat(website): Add simple docs

website/client/.vitepress/config.mts
=> feat(website): Add discord icon

README.md
=> docs(readme): Tweak Alternative Tools section layout

src/cli/actions/remoteAction.ts, tests/cli/actions/remoteAction.test.ts
=> fix(remote): update repository name pattern validation

.github/workflows/ci.yml
=> ci(test): Remove test from needs in test-coverage

.github/workflows/docker.yml
=> chore(docker): Add ARM platform support for container images

website/client/.vitepress/config/configShard.ts
=> fix(website): Change sitemap URL from http to https

.github/copilot-instructions.md, README.md, repomix-instruction.md, website/client/package-lock.json, website/client/src/en/guide/installation.md, website/client/src/es/guide/installation.md, website/client/src/ja/guide/installation.md, website/client/src/ko/guide/installation.md, website/client/src/pt-br/guide/installation.md, website/client/src/zh-cn/guide/installation.md, website/server/cloudbuild.yaml, website/server/package-lock.json
=> docs(website): update website documentation

website/client/.vitepress/config/configShard.ts
=> docs(website): Add link to X in website

website/server/src/index.ts, website/server/src/utils/processConcurrency.ts
=> feat(website): Log the number of servers in parallel

README.md
=> docs(readme): Separate privacy policy for README from CLI and repomix.com

website/client/components/TryItResultViewer.vue
=> feat(website): Add support for dark theme to website's ace editor

package-lock.json, package.json
=> chore(deps): Apply fixes for vulnerabilities resolved by npm audit fix

src/cli/actions/defaultAction.ts, src/cli/actions/remoteAction.ts, src/cli/cliRun.ts, src/cli/cliSpinner.ts, src/cli/types.ts, src/config/configLoad.ts, src/core/file/workers/fileCollectWorker.ts, src/index.ts, src/shared/logger.ts, tests/cli/actions/defaultAction.test.ts, tests/cli/cliRun.test.ts, tests/config/configLoad.test.ts, tests/core/file/fileCollect.test.ts, tests/shared/logger.test.ts
=> feat(cli): Add quiet mode option

src/cli/cliRun.ts, src/index.ts, src/shared/logger.ts, tests/cli/cliRun.test.ts
=> feat(index): Add additional export to treat as a library

repomix.config.json, website/server/src/index.ts, website/server/src/utils/logger.ts, website/server/src/utils/time.ts
=> fix(website): Fix output method of latency

src/core/treeSitter/parseStrategies/GoParseStrategy.ts, src/core/treeSitter/parseStrategies/PythonParseStrategy.ts, src/core/treeSitter/parseStrategies/TypeScriptParseStrategy.ts, src/core/treeSitter/queries/queryTypescript.ts
=> refactor(compress): Refactor file compression strategy

README.md, package-lock.json, package.json, src/cli/actions/mcpAction.ts, src/cli/cliRun.ts, src/cli/types.ts, src/core/file/fileSearch.ts, src/core/mcp/mcpServer.ts, src/core/mcp/tools/packCodebaseTool.ts, src/core/mcp/tools/packRemoteRepositoryTool.ts
=> feat(mcp): Initial implementation of the MCP server

README.md, website/client/.vitepress/config/configDe.ts, website/client/.vitepress/config/configEnUs.ts, website/client/.vitepress/config/configEs.ts, website/client/.vitepress/config/configJa.ts, website/client/.vitepress/config/configKo.ts, website/client/.vitepress/config/configPtBr.ts, website/client/.vitepress/config/configZhCn.ts, website/client/src/de/guide/mcp-server.md, website/client/src/en/guide/mcp-server.md, website/client/src/es/guide/mcp-server.md, website/client/src/ja/guide/mcp-server.md, website/client/src/ko/guide/mcp-server.md, website/client/src/pt-br/guide/mcp-server.md, website/client/src/zh-cn/guide/mcp-server.md
=> docs(readme): Add MCP Server docs

README.md, llms-install.md, website/client/src/de/guide/mcp-server.md, website/client/src/en/guide/mcp-server.md, website/client/src/es/guide/mcp-server.md, website/client/src/ja/guide/mcp-server.md, website/client/src/ko/guide/mcp-server.md, website/client/src/pt-br/guide/mcp-server.md, website/client/src/zh-cn/guide/mcp-server.md
=> docs(mcp): Add llms-install.md

.github/copilot-instructions.md, src/core/mcp/tools/packCodebaseTool.ts, src/core/mcp/tools/packRemoteRepositoryTool.ts
=> feat(mcp): Return packing metrics as well and refine description

src/core/treeSitter/ext2Lang.ts, src/core/treeSitter/lang2Query.ts, src/core/treeSitter/parseStrategies/CssParseStrategy.ts, src/core/treeSitter/parseStrategies/ParseStrategy.ts, src/core/treeSitter/parseStrategies/VueParseStrategy.ts, src/core/treeSitter/queries/queryCss.ts, src/core/treeSitter/queries/queryVue.ts, tests/core/treeSitter/parseFile.css.test.ts, tests/core/treeSitter/parseFile.vue.test.ts
=> feat(compress): Add Vue, CSS file support for compress mode

README.md, repomix.config.json, src/cli/actions/defaultAction.ts, src/cli/cliRun.ts, src/cli/types.ts, src/config/configSchema.ts, src/core/file/filePathSort.ts, src/core/file/gitCommand.ts, src/core/output/outputGenerate.ts, src/core/output/outputSort.ts, src/core/output/outputStyleDecorate.ts, src/core/packager.ts, src/mcp/mcpServer.ts, tests/cli/actions/defaultAction.test.ts, tests/cli/actions/mcpAction.test.ts, tests/cli/cliRun.test.ts, tests/config/configSchema.test.ts, tests/core/file/gitCommand.test.ts, tests/core/output/outputGenerate.test.ts, tests/core/output/outputSort.test.ts, tests/core/packager.test.ts, tests/core/treeSitter/loadLanguage.test.ts, tests/integration-tests/packager.test.ts, tests/mcp/mcpServer.test.ts, tests/mcp/tools/fileSystemReadDirectoryTool.test.ts, tests/mcp/tools/fileSystemReadFileTool.test.ts, tests/mcp/tools/packCodebaseTool.test.ts, tests/testing/testUtils.ts
related: 
- https://github.com/yamadashy/repomix/issues/356
=> feat(git): Sort files by git commit frequency

website/client/package-lock.json
=> chore(deps): update deps

src/config/defaultIgnore.ts
=> feat(ignore): Add uv.lock to default ignore

README.md, website/client/.vitepress/config.ts, website/client/.vitepress/config/configFr.ts, website/client/components/Home/TryIt.vue, website/client/components/Home/TryItFolderUpload.vue, website/client/src/en/guide/usage.md, website/client/src/fr/guide/code-compress.md, website/client/src/fr/guide/command-line-options.md, website/client/src/fr/guide/comment-removal.md, website/client/src/fr/guide/configuration.md, website/client/src/fr/guide/custom-instructions.md, website/client/src/fr/guide/development/index.md, website/client/src/fr/guide/development/setup.md, website/client/src/fr/guide/index.md, website/client/src/fr/guide/installation.md, website/client/src/fr/guide/mcp-server.md, website/client/src/fr/guide/output.md, website/client/src/fr/guide/prompt-examples.md, website/client/src/fr/guide/remote-repository-processing.md, website/client/src/fr/guide/security.md, website/client/src/fr/guide/tips/best-practices.md, website/client/src/fr/guide/usage.md, website/client/src/fr/index.md
=> docs(website): Add french documents

src/core/file/fileManipulate.ts, src/core/treeSitter/ext2Lang.ts, src/core/treeSitter/lang2Query.ts, src/core/treeSitter/queries/queryGo.ts, src/core/treeSitter/queries/queryJava.ts, src/core/treeSitter/queries/queryPython.ts, src/core/treeSitter/queries/queryRuby.ts, src/core/treeSitter/queries/queryRust.ts, src/core/treeSitter/queries/querySolidity.ts, tests/core/treeSitter/LanguageParser.test.ts, tests/core/treeSitter/parseFile.c.test.ts, tests/core/treeSitter/parseFile.ruby.test.ts, tests/core/treeSitter/parseFile.solidity.test.ts, tests/core/treeSitter/parseFile.swift.test.ts
=> feat(compress): Compress now supports solidity

package-lock.json, package.json, website/client/package-lock.json
=> chore(deps): Update vite

website/client/components/Home/TryIt.vue, website/client/components/Home/TryItPackOptions.vue, website/client/components/api/client.ts, website/client/components/utils/analytics.ts, website/server/package-lock.json, website/server/src/processZipFile.ts, website/server/src/remoteRepo.ts, website/server/src/schemas/request.ts, website/server/src/types.ts
=> feat(website): implement compress functionality on website

README.md, website/client/src/de/guide/mcp-server.md, website/client/src/en/guide/mcp-server.md, website/client/src/es/guide/mcp-server.md, website/client/src/fr/guide/mcp-server.md, website/client/src/ja/guide/mcp-server.md, website/client/src/ko/guide/mcp-server.md, website/client/src/pt-br/guide/mcp-server.md, website/client/src/zh-cn/guide/mcp-server.md
Hi 👋 Burke Holland from the VS Code team here.
Next week we're shipping MCP support in VS Code, and would love to have support for it on Repomix. This PR adds instructions and install buttons to the README. Thanks again for the great project!
=> Support for installing servers in VS Code

README.md, website/client/src/de/guide/mcp-server.md, website/client/src/en/guide/mcp-server.md, website/client/src/es/guide/mcp-server.md, website/client/src/fr/guide/mcp-server.md, website/client/src/ja/guide/mcp-server.md, website/client/src/ko/guide/mcp-server.md, website/client/src/pt-br/guide/mcp-server.md, website/client/src/zh-cn/guide/mcp-server.md
=> docs(website): Adjust MCP documentation. Move installation to the top.

README.md
=> docs(readme): Add cursor mcp setting

README.md
=> docs(readme): Adjust MCP install badges

README.md
=> docs(readme): Add tiktoken explanation

README.md
=> docs(readme): adjust VSCode extension description

tests/cli/actions/defaultAction.test.ts, tests/cli/actions/initAction.test.ts, tests/cli/actions/remoteAction.test.ts, tests/core/treeSitter/parseFile.css.test.ts
=> test: Remove stdout when running test

README.md
- https://github.com/yamadashy/repomix/issues/473
=> Fix: Update BACK TO TOP link in README.md (#473)

website/client/package-lock.json
=> chore(deps): update vite to 5.4.18

repomix.config.json, src/config/configLoad.ts, src/config/configSchema.ts, src/core/file/fileCollect.ts, src/core/file/workers/fileCollectWorker.ts, src/core/file/workers/fileProcessWorker.ts, src/core/metrics/workers/fileMetricsWorker.ts, src/core/metrics/workers/outputMetricsWorker.ts, src/core/packager.ts, src/core/security/workers/securityCheckWorker.ts, src/shared/logger.ts, src/shared/processConcurrency.ts, tests/cli/actions/defaultAction.test.ts, tests/cli/cliRun.test.ts, tests/config/configSchema.test.ts, tests/core/file/fileCollect.test.ts, tests/core/packager.test.ts, tests/core/treeSitter/parseFile.solidity.test.ts, tests/integration-tests/packager.test.ts, tests/mcp/tools/packCodebaseTool.test.ts, tests/shared/processConcurrency.test.ts, tests/testing/testUtils.ts
ref
- https://github.com/yamadashy/repomix/issues/437
=> feat: allow setting max file size

tests/core/file/fileProcessContent.test.ts, tests/core/metrics/calculateOutputMetrics.test.ts, tests/core/packager/copyToClipboardIfEnabled.test.ts
=> test(core): Improve test coverage for copyToClipboardIfEnabled

README.md
=> docs(readme): add DeepWiki badge

website/client/src/de/guide/github-actions.md, website/client/src/en/guide/github-actions.md, website/client/src/es/guide/github-actions.md, website/client/src/fr/guide/github-actions.md, website/client/src/ja/guide/github-actions.md, website/client/src/ko/guide/github-actions.md, website/client/src/pt-br/guide/github-actions.md, website/client/src/zh-cn/guide/github-actions.md, website/client/src/zh-tw/guide/github-actions.md
=> Put link on the text in github-actions.md

website/client/components/Home/TryItResultErrorContent.vue
Clarify the link text in the TryItResultErrorContent component to improve user understanding.
=> Update link text for clarity in TryItResultErrorContent component

CLAUDE.md, README.md, website/client/src/de/guide/installation.md, website/client/src/de/index.md, website/client/src/en/guide/installation.md, website/client/src/en/index.md, website/client/src/es/guide/installation.md, website/client/src/es/index.md, website/client/src/fr/guide/installation.md, website/client/src/fr/index.md, website/client/src/hi/guide/installation.md, website/client/src/hi/index.md, website/client/src/id/guide/installation.md, website/client/src/id/index.md, website/client/src/ja/guide/installation.md, website/client/src/ja/index.md, website/client/src/ko/guide/installation.md, website/client/src/ko/index.md, website/client/src/pt-br/guide/installation.md, website/client/src/pt-br/index.md, website/client/src/vi/guide/installation.md, website/client/src/vi/index.md, website/client/src/zh-cn/guide/installation.md, website/client/src/zh-cn/index.md, website/client/src/zh-tw/guide/installation.md, website/client/src/zh-tw/index.md, website/server/cloudbuild.yaml
Increase CPU allocation in Cloud Build configuration to improve server performance. Enhance CLAUDE.md with a comprehensive architecture guide and add Bun installation instructions to the documentation.
=> Increase Cloud Run CPU allocation and enhance documentation

src/core/file/fileSearch.ts, tests/core/file/fileSearch.test.ts
Enhance the user authentication process by streamlining login and registration, improving error handling, and adding validation checks.
=> Improve user authentication flow

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/init-firewall.sh
This PR adds a comprehensive devcontainer setup specifically optimized for Claude Code development with enhanced security features.
- **Custom Dockerfile**: Creates a Node.js-based development environment with Claude Code pre-installed
- **Security-hardened setup**: Implements a firewall configuration that restricts network access to only trusted domains (GitHub, npm registry, Anthropic APIs, etc.)
- **Development tools**: Includes essential tools like `gh`, `jq`, `fzf`, `delta`, and configures zsh with oh-my-zsh
- **VS Code integration**: Pre-configures extensions and settings for optimal Claude Code development experience
- **Persistent storage**: Maintains bash history and Claude configuration across container restarts
The container includes a sophisticated firewall script …
=> chore(devcontainer): add Claude Code dev container setup
